INTERNAL_SERVER_ERROR:
  code: 500
  message: "内部服务器错误!"
  debug: "Internal server error: {error}"

PERMISSION_DENIED:
  code: 403
  message: "无请求权限!"
  debug: "无请求权限: {error}"

Unauthorized:
  code: 401
  message: "用户未验证!"
  debug: "用户未验证:{error}"

LOAD_WRONG_TYPE:
  code: 500
  message: "加载的数据类型不符合"

DeadlineExceeded:
  code: 408
  message: "请求超时,请刷新重试"

GRPCUnavailable:
  code: 503
  message: "请求超时,请刷新重试"