appname: gst-gateway
listen: ":18000"
appmode: release
log:
  file:
    filename: runtime/gateway.log
    maxsize: 100
    maxbackups: 3
    maxage: 28
    level: 1 #debug:-1;info:0;warning:1;error:2;DPanic:3;Panic:4;Fatal:5

error-template: config/errors.zh.yaml

cache:
  dataloader:
    type: local

web:
  staticdir: "public"

jwt:
  enable: false
  public-key: "" # pem file if use rs algorithm
  encryption-key: "abcderf"
  algorithm: "HS256"

auth:
  auth-server: ""
  check-access: ""
  check-access-timeout: 1000 #microsecond
  router-prefix: ""

#opentracing:
#  sampler:
#    type: const
#    param: 1
#  reporter:
#    logSpans: false
#    localAgentHostPort: "127.0.0.1:6831"
#  headers:
#    TraceContextHeaderName: trace.traceid

rpc:
  greeter:
    name: :18001 # if use etcd ,the rpc connection will be: qeelyn://author/srv-greeter
