appname: srv-greeter
listen: ":18001"
registryListen: ":18001"
appmode: release
log:
  file:
    filename: runtime/greeter.log
    maxsize: 100
    maxbackups: 3
    maxage: 28
    level: 1 #debug:-1;info:0;warning:1;error:2;DPanic:3;Panic:4;Fatal:5

error-template: config/errors.zh.yaml

db:
  default:
    dialect: postgres
    dsn: host=host port=5432 user= dbname=advisorq_mtdb password= sslmode=disable

auth:
  auth-server: ""
  check-access: ""
  check-access-timeout: 1000 #microsecond
  public-key: config/rsa_pub.pem
  router-prefix: ""

opentracing:
  sampler:
    type: const
    param: 1
  reporter:
    logSpans: false
    localAgentHostPort: "127.0.0.1:6831"

metrics:
  backend: prometheus